### PR TITLE
category field added, all category urls are working now.

### PR DESCRIPTION
**Pull request by Ak-shay**
This PR have following functionality added:
Category field is added to Post model
all category urls are working now
added Meta class to Post for ordering

### CODE REVIEW

**Review by ighosh98 — APPROVED** [review]
@abhishekspeer review if you want any changes. @Ak-shay Add documentation for the nomenclature and the features added in the PR

**Comment by Ak-shay** [comment]
created a Category model
Now a post can have more than one categories
added pagination, 'older posts' and 'newer post' buttons are working now.

**Review by ighosh98 — CHANGES_REQUESTED** [review]
@Ak-shay Add the documentation as mentioned in issue #49 . We should be good to go after that.

**Comment by ighosh98** [comment]
Documentation must be added later as discussed in #49

**Pull request merged**
