### PR TITLE
Articles, Animations and  Profile Page template added, Comments section modified, Bugs Fixed

### PR DESCRIPTION
**Pull request by ighosh98**
Check out these Issues @Ak-shay :
- [x] Handle integrity errors. They are raised when an article of the same title is added. 
- [x] I am unable to add images on my articles inside the post. (Test using the backend of the old website. Use [this article](http://www.freelunch.co.in/wp-admin/post.php?post=2167&action=edit) as sample)
- [x] Cover image is not being displayed even after it is uploaded.
- [x] This page is getting displayed
Screenshot from 2019-06-26 23-03-28
when you click on Visit on Site.
Screenshot from 2019-06-26 23-04-33

- [x]  Remove the cards format for the article.
Screenshot from 2019-06-26 23-19-10

The preferred format has been discussed with you @Ak-shay 

- [x] Modify the writers model to add the editor's profiles(Editor-in-Chief etc.) as well. We will modify the contributor's page accordingly.

### CODE REVIEW

**Comment by Ak-shay** [comment]
@ighosh98 
Have a look

**Comment by Ak-shay** [comment]
For point 4
u need to add settings of sites 
go to admin page, open sites model, add `domain name` = `127.0.0.1:8000`

**Comment by Ak-shay** [comment]
Please elaborate the last point..
Its bit confusing

**Comment by ighosh98** [comment]
I will do that. @Ak-shay

**Comment by Ak-shay** [comment]
An important for adding image in between content..
Please use enter(one line gap) before and after image is added

**Comment by ighosh98** [comment]
Fix the card-based format @Ak-shay. We are good to go.

**Comment by Ak-shay** [comment]
@HimanshuAgarwal022 
Are you working on profile page?

**Comment by Ak-shay** [comment]
What about pagination post list?

**Comment by ighosh98** [comment]
Infinite scroll has been implemented instead. Articles would keep on leading as you scroll down.

**Comment by Ak-shay** [comment]
okay..
should I delete pagination from backend then?

**Comment by Ak-shay** [comment]
fixes #116

**Comment by unlaxedneurotic** [comment]
Included a local image to show a problem in masthead. check posts 'what narcos doesn't tell you' or 'Automated image labelling...' .
Now posts show their own cover image in post list

**Comment by ighosh98** [comment]
@UnlaxedNeurotic please create an issue for the same.

**Comment by ighosh98** [comment]
> okay..
> should I delete pagination from backend then?

Yes delete it @Ak-shay

**Comment by Ak-shay** [comment]
see #120

**Comment by ighosh98** [comment]
Resolved all major conflicts and solved #119

**Comment by ighosh98** [comment]
Merge when #126 is solved. @Ak-shay @HimanshuAgarwal022  please solve that issue.

**Comment by Ak-shay** [comment]
add image `default_cover.jpeg` inside media dir

**Comment by ighosh98** [comment]
All issues solved. I'll merge this.

**Pull request merged**
