### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by unlaxedneurotic**

### CODE REVIEW

**Comment by ighosh98** [comment]
@UnlaxedNeurotic Add instructions for allowing people to set it up locally as instructed in  issue #14 . Also, whenever you send a PR add a short description(At least address which is the issue being solved)

**Review by ighosh98 — COMMENTED** [review]
Add instructions on how to build the project locally.

**Comment by unlaxedneurotic** [comment]
Updated the README to include instructions for setting up the project locally

**Comment by abhishekspeer** [comment]
We might want to make some changes in future but this looks good to me for now. Great work @UnlaxedNeurotic! :)
Merging #29

**Review by abhishekspeer — APPROVED** [review]

**Pull request merged**
