### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Ak-shay**
@ighosh98 
@abhishekspeer 
review it.

### CODE REVIEW

**Comment by ighosh98** [comment]
@Ak-shay  Resolve all the conflicts first. Let me know when you're done

**Comment by Ak-shay** [comment]
@ighosh98  resolved

**Review by ighosh98 — CHANGES_REQUESTED** [review]
Add another model for Article content as discussed in #3 . Solve as much of the issue as you can in this PR. We'll squash and merge it at the end.

**Comment by ighosh98** [comment]
Add documentation as mentioned in #49 .

**Comment by ighosh98** [comment]
Add documentation later by creating a new PR for solving #49

**Comment by ighosh98** [comment]
Merged to master. May make the branch temporarily unstable.

**Pull request merged**
