### PR TITLE
Updating Master

### PR DESCRIPTION
**Pull request by ighosh98**
Check views.py @Ak-shay once

### CODE REVIEW

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 To clone only development use the following 
`git clone --single-branch --branch development https://github.com/BITS-Periodical-Society/freelunch.git
`
Please commit your code by tomorrow afternoon.

**Comment by Ak-shay** [comment]
With this new commit, TinyMCE was replaced with pagedown libraries..

**Comment by ighosh98** [comment]
I will try and see if the code breaks. Good job @Ak-shay. I need you to comment the necessary links on issue #56  so that I can review them before merging.

**Comment by ighosh98** [comment]
So, I tried out stuff with your committed code. 
@Ak-shay a few suggestions
1. Do not allow the writer to add an article. I'll explain with an image:
Screenshot from 2019-06-23 12-45-28

In the image if you zoom in you would see a '+' beside the post option. Remove that '+' from there. Same goes for the editors section.
Screenshot from 2019-06-23 12-47-25


My reason: A person may click on editor and then click on new article and then enter some writer. Then he could enter the article there, close eveything and again enter the article. This would create duplicates. I will explain this over a call if the explanation does not make sense. 

Simply speaking there are certain corner cases that need to be sorted out.
Try handling these cases.
2. Lists are having a difference in the HTML Preview vs the real post when they are not numbered[We want it to look like the HTML preview]. See if we can counter this issue
For reference, Have a look at these images.

HTML Preview 
Screenshot from 2019-06-23 13-00-21

The Actual Post
Screenshot from 2019-06-23 13-00-25

3. Can we do something about the font? Give the editor a few more options for the font.[Not necessary to be implemented. The current font looks alright. But it would be nice if we could test a couple more fonts and decde which works best]
4.We need a cover image for every article. This need not be implemented immediately. I will work on this later.
 
Everything else works great. Images are getting added perfectly.

**Comment by ighosh98** [comment]
Issues created. #86 can be solved later. Try to solve #84 and #85 so that I can merge the PR

**Comment by ighosh98** [comment]
@Ak-shay Explain the category dict model for sections once. Would it store a mapping from section to tags?

**Pull request merged**
