### PR TITLE
[WIP] Fix All frontend bugs

### LINKED ISSUE #173: Add gap between 2 Articles
Screenshot from 2019-07-06 20-30-52

Add some gap between 2 articles to make sure users can differentiate between 2 articles while scrolling.
Also, add some gap between image and article content.

### LINKED ISSUE #176: Customise the Article List View
Although the front heading looks good, the articles list view doesn't look that good at the moment. 
Make necessary changes to improve the design.

### PR DESCRIPTION
**Pull request by Ak-shay**
- [ ] Infinite Scroll
- [x] Make it responsive
- [x] Edit Masterhead
- [x] Fix Footer

fixes #176 
fixes #173

### CODE REVIEW

**Comment by Ak-shay** [comment]
@HimanshuAgarwal022 @ighosh98 @UnlaxedNeurotic

**Comment by ighosh98** [comment]
I'll start working on the infinite scroll issue

**Comment by ighosh98** [comment]
Fixes #180.

**Comment by ighosh98** [comment]
Fixes #100. @Ak-shay  have a look and suggest changes if any.

**Pull request merged**
