### PR TITLE
[WIP] sendgrid setup

### PR DESCRIPTION
**Pull request by Ak-shay**
I am having a import error in email.py 
```bash
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/akshay/freelunch/myvenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/akshay/freelunch/myvenv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/akshay/freelunch/myvenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/home/akshay/freelunch/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/akshay/freelunch/myvenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/akshay/freelunch/myvenv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/akshay/freelunch/myvenv/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/akshay/freelunch/myvenv/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/akshay/freelunch/flapp/models.py", line 11, in <module>
    from .email import email_for_subscribers
  File "/home/akshay/freelunch/flapp/email.py", line 8, in <module>
    from .models import Subscriber
ImportError: cannot import name 'Subscriber' from 'flapp.models' (/home/akshay/freelunch/flapp/models.py)
```

### CODE REVIEW

**Comment by ighosh98** [comment]
@Ak-shay check if everything works. Circular dependency.

**Comment by ighosh98** [comment]
Fixes #200.

**Comment by ighosh98** [comment]
@Ak-shay merge if everything is done

**Comment by Ak-shay** [comment]
Unsubsrcibe button is not working.

**Comment by Ak-shay** [comment]
If we dont need unsubscribe button then we are good to go.

**Comment by ighosh98** [comment]
We need to add unsubscribe

**Pull request merged**
