### PR TITLE
Front end changes

### PR DESCRIPTION
**Pull request by ighosh98**
@HimanshuAgarwal022  comment when you are done

### CODE REVIEW

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 also increase the text size in post detail

**Comment by ighosh98** [comment]
Fixes #128 , #31.

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 Please fix #151. Let me know when you are done. We can merge this PR then.

**Comment by HimanshuAgarwal022** [comment]
all done!
you can merge now.

**Comment by HimanshuAgarwal022** [comment]
@ighosh98

**Comment by ighosh98** [comment]
The template still needs to be modified to make it compatible with backend. Rest is fine.

**Comment by Ak-shay** [comment]
The border on home page for list of posts is not looking...
Actually the shadow is not good..
Screenshot from 2019-07-04 22-07-21

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 please fix that. Add the sliders to the side of the image instead of it being at the top. You can look up other websites for ideas.

**Comment by ighosh98** [comment]
Merging. Fix bugs addressed in #159 in another PR.

**Pull request merged**
