### PR TITLE
Further improved readme in accordance with issue #30

### PR DESCRIPTION
**Pull request by unlaxedneurotic**
Commit to resolve issue #30

### CODE REVIEW

**Comment by ighosh98** [comment]
@UnlaxedNeurotic Add further details for building the project. Assume that the user does not have any of the dependencies installed and add steps for that. Rest is fine.

**Review by ighosh98 — CHANGES_REQUESTED** [review]
@UnlaxedNeurotic Add further details for building the project. Assume that the user does not have any of the dependencies installed and add steps for that. Rest is fine.

**Review by abhishekspeer — APPROVED** [review]
Looks good for now!

**Comment by abhishekspeer** [comment]
@UnlaxedNeurotic To add build guide you can use this as a reference:
https://github.com/abhishekspeer/Google-Login

**Comment by unlaxedneurotic** [comment]
Changes made as requested.

**Comment by ighosh98** [comment]
Good Job @UnlaxedNeurotic! Merging PR for solving #30.

**Pull request merged**
