### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by ighosh98**
Addressing #13 . 
The issue was solved by @HimanshuAgarwal022

### CODE REVIEW

**Comment by abhishekspeer** [comment]
@ighosh98 you have referenced this with #19 `(Add Issue Template)` but this PR is related to adding requirements.txt. If possible please change that.
EDIT: Addressing #13

**Review by abhishekspeer — CHANGES_REQUESTED** [review]
@HimanshuAgarwal022 When we add a requirements.txt file, we are only supposed to include the packages/libraries we want to use and NOT its dependencies.
A dependency is a package REQUIRED by a package we we primarily want to use. Hence, when we install a package, it checks if we already have the dependencies installed or not. If not, these dependencies are installed as well.
For Instance: 
Here, pytz and sqlparse are one of the dependencies used by django (our primary package) and hence are installed on their own if we install Django. We are not supposed to include these in the requirements.txt.
Make necessary changes and commit again.
Hope it helps!

**Comment by ighosh98** [comment]
I'll work on this issue. Made the changes suggested in addressing the issue.

**Comment by ighosh98** [comment]
Made changes. @abhishekspeer  review it and suggest changes if any.
@HimanshuAgarwal022  
Points to note: 
1. If you are not doing the project in a unique virtualenv do not use the command
``` pip freeze > requirements.txt ``` This typically creates a requirements.txt for all packages installed in your virtualenv, some of which maybe unecessary.
**Solution: Use [pipreqs](https://github.com/bndr/pipreqs) instead.**

**Comment by ighosh98** [comment]
@abhishekspeer The issue is solved. I'll merge it. If required we can create a new Pull request to make further changes.

**Comment by ighosh98** [comment]
@Ak-shay please refer to my comment on pipreq.

**Pull request merged**
