### PR TITLE
Faker Script Fixed

### PR DESCRIPTION
**Pull request by unlaxedneurotic**
Fixes issue #153
@ighosh98

### CODE REVIEW

**Comment by unlaxedneurotic** [comment]
Now, each post will have either one or two (at random) authors

**Comment by ighosh98** [comment]
@UnlaxedNeurotic Please upload a few screenshots and edit the README with instructions on how to run the faker script[**Create a new subtopic call "For Developers" and add these instructions**]
Upload these photos on the README as well. That's all.

**Comment by unlaxedneurotic** [comment]
I have already updated the README.md. Please clarify what kind of screenshots should I upload

**Comment by ighosh98** [comment]
Run the faker script add an image of the output.

**Comment by ighosh98** [comment]
Fixes #153.

**Pull request merged**
