### PR TITLE
All models are added. TinyMCE setup is done.

### LINKED ISSUE #45: Models to handle to diff kind of users, their permissions and basic info.
We have a page 'about'  in which we will show some basic info like name, email, bio ...etc
This page will have list of all users (developers, editors, chief-editor..etc).
We can have two types user which have any permissions and other with none. But their info will be their in db.
First we need to gather info about types of users and their permissions.
Then ideas to manage to them all.

### LINKED ISSUE #56: changing post content field to something easy to beautify its content
I have come across an  applicaion [tinyMCE](https://www.tiny.cloud/) for the same.
[Here](https://fosstack.com/how-to-set-up-tinymce-in-django-app/) is the tutorial for same.
More ideas are welcome.

### PR DESCRIPTION
**Pull request by Ak-shay**
models are added.
TinyMCE setup is done.
tempalates are connected.
media is configurations is also done.
fixes #56
fixes #45

### CODE REVIEW

**Comment by Ak-shay** [comment]
@ighosh98 
We need different templates for editor and developer info.
Also do something of css class "column1". Its difficult to apply loop.

**Comment by ighosh98** [comment]
I'll create an issue for that. Hopefully, there's a workaround. 
**Note**
Until @abhishekspeer  approves the changes. Everyone is supposed to wokr on this branch only or make PRs into this branch. 
CC: @Ak-shay @UnlaxedNeurotic @HimanshuAgarwal022 @JessePinkman7 
In case it's not clear, the branch is templates-backend.

**Review by ighosh98 — COMMENTED** [review]
Everything other than TinyMCE looks fine. I will read up on it before I make a call on TinyMCE. 
Requesting review @abhishekspeer.

**Review by ighosh98 — CHANGES_REQUESTED** [review]
On running the code locally, the following error popped up.
ModuleNotFoundError: No module named 'tinymce'

**Comment by Ak-shay** [comment]
We have two new requirements.. So u need to install them..

**Comment by ighosh98** [comment]
Tasks left:  We need row classes to be repeated after 3 cycles.
@HimanshuAgarwal022 in reference to issue #69 .
Search for custom tags in Django to solve this issue.(<% cycle....>, for example, works as a for loop

**Comment by ighosh98** [comment]
@Ak-shay Look at the other alternatives for  TinyMCE on #56 .

**Review by ighosh98 — CHANGES_REQUESTED** [review]
@Ak-shay The formatting of the article isn't coming out right as of now. Check the article added to the database instead of topic-4.

**Comment by ighosh98** [comment]
Merging #68

**Pull request merged**
